language: python
services:
  - xvfb
  - mysql
python:
    - "3.5"
before_install:
    - "export DISPLAY=:99"
    - mysql -e 'set global wait_timeout=3600'
install:
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "pip install mysqlclient==1.4.6"
script:
    - pycodestyle mentoring --max-line-length=120
    - pylint tests
    # Run pylint on any modified .py files but since there are a lot of issues right now, don't make it fail the build:
    #- "(xargs pylint || echo -e \\\\nWARNING: PYLINT ERRORS) || echo pylint skipped"
    - pytest tests/unit --ds=settings_travis
notifications:
  email: false
addons:
  firefox: "72.0.2"
